In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import accuracy_score, log_loss, recall_score, precision_score, f1_score

In [36]:
df = pd.read_csv("churn.csv")
df.head(10)

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,15574012,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,15592531,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,15656148,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,15792365,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,15592389,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [37]:
df['churn'].value_counts()

churn
0    7963
1    2037
Name: count, dtype: int64

In [38]:
a = 7963
b = 2037
percentage_1 = (a/(a+b))*100
print(percentage_1)
percentage_2 = (b/(a+b))*100
print(percentage_2)

79.63
20.369999999999997

In [45]:
df = df.drop(['country','gender'], axis = 1)
df_churned = df[df['churn'] == 1]
df_churned.head(10)

,customer_id,credit_score,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,42,2,0.00,1,1,1,101348.88,1
2,15619304,502,42,8,159660.80,3,1,0,113931.57,1
5,15574012,645,44,8,113755.78,2,1,0,149756.71,1
7,15656148,376,29,4,115046.74,4,1,0,119346.88,1
16,15737452,653,58,1,132602.88,1,1,0,5097.67,1
22,15699309,510,38,4,0.00,1,1,0,118913.53,1
30,15589475,591,39,3,0.00,3,1,0,140469.38,1
35,15794171,475,45,0,134264.04,1,1,0,27822.99,1
41,15738148,465,51,8,122522.32,1,0,0,181297.65,1
43,15755196,834,49,2,131394.56,1,0,0,194365.76,1

In [48]:
df_churned_1 = df.drop(['churn' , 'balance'], axis = 1)
df_churned_1.head()

,customer_id,credit_score,age,tenure,products_number,credit_card,active_member,estimated_salary
0,15634602,619,42,2,1,1,1,101348.88
1,15647311,608,41,1,1,0,1,112542.58
2,15619304,502,42,8,3,1,0,113931.57
3,15701354,699,39,1,2,0,0,93826.63
4,15737888,850,43,2,1,1,1,79084.10

In [49]:
df_churned_1 = pd.get_dummies(df_churned_1 , drop_first = True)
df_churned_1.head()

,customer_id,credit_score,age,tenure,products_number,credit_card,active_member,estimated_salary
0,15634602,619,42,2,1,1,1,101348.88
1,15647311,608,41,1,1,0,1,112542.58
2,15619304,502,42,8,3,1,0,113931.57
3,15701354,699,39,1,2,0,0,93826.63
4,15737888,850,43,2,1,1,1,79084.10

In [50]:
y = df_churned['churn']
x = df_churned.copy()
x = x.drop(['balance'], axis = 1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42, stratify = y)

In [51]:
decision_tree = DecisionTreeClassifier(random_state = 42)
decision_tree.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [54]:
decision_tree = DecisionTreeClassifier(random_state = 42)
decision_tree.fit(x_train, y_train)
pred = decision_tree.predict(x_test)

print("Accuracy:" , "%.3f"% accuracy_score(y_test, pred))
print("Recall Score:" , "%.3f"% recall_score(y_test, pred))
print("Precision Score:" , "%.3f"% precision_score(y_test, pred))
print("F1 Score:" , "%.3f"% f1_score(y_test, pred))

Accuracy: 1.000
Recall Score: 1.000
Precision Score: 1.000
F1 Score: 1.000